import { atom } from "nanostores";

export type ModalType =
  | "CLOSE_MODAL"
  | "UPDATE_EMAIL_MODAL"
  | "UPDATE_PHONE_NUMBER_MODAL"
  | "OTP_MODAL"
  | "ACCOUNT_DETAILS_MODAL"
  | "ACCOUNT_RECONNECT_MODAL"
  | "ACCOUNT_LIMIT_MODAL"
  | "PROXY_ACCOUNT_MODAL"
  | "ADD_ACCOUNT_MODAL"
  | "VERIFY_ACCOUNT_MODAL"
  | "DELETE_ACCOUNT_MODAL"
  | "ADD_BLOCKLIST_MODAL"
  | "POST_RECEIVED_MODAL"
  | "PAYOUT_MODAL"
  | "DELETE_LEAD_MODAL"
  | "IMPORT_LEAD_MODAL"
  | "POST_SOURCE_MODAL"
  | "STRIPE_ADDONS_PAYMENT_MODAL"
  | "SETUP_CAMPAIGN_ACTION_MODAL"
  | "DM_AUTOMATION_DELETE_MODAL"
  | "DM_AUTOMATION_MULTI_DELETE_MODAL"
  | `DM_AUTOMATION_ACTION_MODAL_${string}`
  | "DM_CAMPAIGNS_RANDONMIZATION_MODAL"
  | "DM_CAMPAIGNS_AB_CONFIGURATION_MODAL"
  | `FOLLOW_UP_AB_CONFIGURATION_MODAL_${number}`
  | "AI_SMART_CONTENT_MODAL"
  | "AI_SMART_CONTENT_BEST_PRACTICES_MODAL"
  | "SUBSCRIPTION_UPGRADE_MODAL"
  | "BUY_CREDITS_STRIPE_ADDONS_PAYMENT_MODAL"
  | "GROWTH_TOOLS_MODAL"
  | "ROADMAP_MODAL"
  | "ROADMAP_VIEW_MODAL"
  | "AI_SMART_CONTENT_MULTI_DELETE_MODAL"
  | `AI_SMART_CONTENT_ACTION_MODAL_${string}`
  | "GROWTH_TOOLS_MULTI_DELETE_MODAL"
  | `GROWTH_TOOLS_ACTION_MODAL_${string}`
  | "STRIPE_ADDONS_PAYMENT_MODAL"
  | "PAYMENT_METHOD_MODAL"
  | "UPLOAD_IMAGE_MODAL"
  | "2FA_MODAL"
  | "INFO_POPUP_MODAL"
  | "BETA_TESTING_MODAL"
  | "LOGOUT_MODAL"
  | "UPDATE_PASSWORD"
  | "REQUEST_FOREVER_PLAN_MODAL"
  | "DOWNLOAD_EXTENSTION_MODAL"
  | "AI_SMART_CONTENT_PROMPT_MODAL"
  | "LEAD_SCRAPING_NO_ACCOUNT_MODAL"
  | "ADVANCED_FILTERS_LOCK_MODAL"
  | "PERSONALIZATION_MODAL"
  | "INSUFFICIENT_CREDIT_MODAL"
  | "CREATE_TEMPLATE_MODAL"
  | "SHOW_TEMPLATE_MODAL"
  | "PREVIEW_DM_MESSAGES"
  | "UPLOAD_DM_AUTOMATION_IMAGE_MODAL"
  | "MESSAGES_MEDIA_PICKER_MODAL"
  | "DELETE_MESSAGES_MODAL"
  | "DM_AUTOMATION_MODAL"
  | "PAYMENT_CHECK_MODAL"
  | "ADVANCED_FILTERS_LOCK_MODAL"
  | "UNBLOCK_ACCOUNT_MODAL";

export const $modalType = atom<ModalType>("CLOSE_MODAL");

export const setModalType = (type: ModalType) => {
  $modalType.set(type);
};

export const $popUpModalInfo = atom<{ title: string; description: string }>({
  title: "",
  description: "",
});
